# -- Site Configuration --

# baseURL = "https://your_domain.com/"
defaultContentLanguage = "en"
publishDir = "public"

title = "Trey Pezzetti Site"

enableRobotsTXT = true
summaryLength = 0

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]
